baseurl = "https://tardigrado.netlify.app/"
defaultContentLanguage = "pt"
landingPageURL='/topics/'
languageCode = "pt-pt"
theme = "hello-friend"
paginate = 5
custom_css = ["style.css"]

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "dark"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.pt]
    title = "Tardigrado"
    keywords = ""
    copyright = ""
    menuMore = "Ver mais"
    writtenBy = "Escrito por"
    readMore = "Ler mais"
    readOtherPosts = "Outros posts"
    newerPosts = "Recentes"
    olderPosts = "Antigos"
    minuteReadingTime = "min"
    dateFormatSingle = "01-02-2006"
    dateFormatList = "01-02-2006"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.pt.params.logo]
      logoText = "tardigrado"
      logoHomeLink = "/topics"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.pt.menu]
      [[languages.pt.menu.main]]
        identifier = "sobre"
        name = "Sobre"
        url = "/about"
      [[languages.pt.menu.main]]
        identifier = "indice"
        name = "Índice"
        url = "/topics"